language: node_js
node_js:
  - "6.10.3"

# Build only "master" and "dev" branches.
# Will also build pull requests to these branches.
branches:
  only:
    - master
    - dev


script:
  - npm run frontend:build
  # After adding custom scripts to build process default command 'npm test' will no longer be executed.
  # Therefore we have to run tests manually.
  - npm run backend:test